### ISSUE TITLE
Link to profiles throws 500 (Internal Server Error)

### ISSUE THREAD

**Issue by xandecelo** [JensRavens/thefetishtraveller#26]
Link to private profiles throws an HTTP 500.

These are same links used at email notifications (aka Daily Summary).

https://thefetishtraveller.com/en/[user_account]

**Comment by JensRavens** [comment]
Do you have an example of a non-working link? My profile seems to work fine: https://thefetishtraveller.com/en/GearUpBerlin

**Comment by xandecelo** [comment]
You can check https://thefetishtraveller.com/en/PupMoto  for example.

**Comment by JensRavens** [comment]
That one works for me when logged in. It does throw a 500 though if you're not logged in. Is that the behaviour you're seeing?

**Comment by xandecelo** [comment]
Yes! 

Maybe I was not clear. You have this links on email (daily digest) and the expected behavior is a click to follow. So, next step should be ask for authentication instead of throwing a 500 Internal server error.
