### ISSUE TITLE
Difficulty posting on iOS device

### ISSUE THREAD

**Issue by socaldan529** [JensRavens/thefetishtraveller#28]
Using both the Safari version and the PWA added to my device from Safari on iOS 15.2 beta I am unable to add a post.

On the Safari version the new post dialog pops up and scrolls properly but the "create post" option won't allow me to click it.

On the Safari PWA version from the Home Screen the dialog for a new post doesn't scroll and render properly and also won't allow me to post if I am able to get it to display the "create post" button by rotating my display to change the orientation.

**Comment by JensRavens** [comment]
Thanks for the detailed report. This was fixed in the last update.
